import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-outfit",
  display: "swap",
});

const _twSafelist = [
  "px-4",
  "text-base",
  "py-2",
  "text-sm",
  "px-8",
  "py-4",
  "text-lg",
  "bg-gradient-to-r",
  "from-purple-500",
  "to-blue-500",
  "text-white",
  "bg-white",
  "text-purple-700",
  "border-2",
  "border-gray-300",
  "text-gray-700",
  "hover:shadow-lg",
  "hover:shadow-xl",
  "hover:-translate-y-0.5",
  "hover:-translate-y-1",
  " hover:text-purple-600",
  "transition-all",
  "duration-200",
  "duration-300",
  "rounded-lg",
  "transform",
  "flex",
  "items-center",
  "justify-center",
  "space-x-2",
].join(" ");

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased {outfit.variable}`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
